let drag=null;
const $all=(s,r=document)=>[...r.querySelectorAll(s)];
function mealType(m){return m?.querySelector('.muted')?.textContent?.trim().toLowerCase()||''}
function clear(){if(!drag)return;clearTimeout(drag.timer);drag.source?.classList.remove('drag-source');drag.ghost?.remove();$all('.day.drag-destination').forEach(x=>x.classList.remove('drag-destination'));document.body.classList.remove('day-dragging');drag=null}
function targetAt(x,y){return document.elementFromPoint(Math.max(1,Math.min(innerWidth-2,x)),Math.max(1,Math.min(innerHeight-2,y)))?.closest('.day')||null}
function mark(x,y){if(!drag)return;$all('.day.drag-destination').forEach(x=>x.classList.remove('drag-destination'));drag.target=targetAt(x,y);if(drag.target&&drag.target!==drag.source)drag.target.classList.add('drag-destination')}
function activate(){if(!drag)return;drag.active=true;drag.source.classList.add('drag-source');document.body.classList.add('day-dragging');const r=drag.source.getBoundingClientRect(),g=drag.source.cloneNode(true);g.querySelectorAll('.day-pair-handle,.day-drag-handle,.menu,.complete').forEach(n=>n.remove());g.className='day drag-day-ghost';Object.assign(g.style,{width:r.width+'px',left:r.left+'px',top:Math.max(8,drag.y-70)+'px'});document.body.appendChild(g);drag.ghost=g;navigator.vibrate?.(30)}
async function finish(x,y){if(!drag)return;mark(x,y);const d=drag,target=d.target?.dataset.date;clear();if(!d.active||!target||target===d.source.dataset.date)return;const msg=document.getElementById('message');if(msg)msg.innerHTML='<div class="status">Moving dinner and linked lunch…</div>';const {createClient}=await import('https://esm.sh/@supabase/supabase-js@2');const cfg=await import('./config.js');const db=createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});const{error}=await db.rpc('move_meal',{target_meal_id:d.mealId,target_date:target});if(error){if(msg)msg.innerHTML=`<div class="status">Could not move: ${error.message}</div>`;return}location.reload()}
function bind(day){day.querySelectorAll('.day-drag-handle').forEach(n=>n.remove());const meals=$all('.meal',day),dinner=meals.find(m=>mealType(m).startsWith('dinner')&&!m.classList.contains('done'));const existing=$all('.day-pair-handle',day);if(!dinner){existing.forEach(n=>n.remove());return}if(existing.length){existing.slice(1).forEach(n=>n.remove());return}const handle=document.createElement('button');handle.type='button';handle.className='day-pair-handle';handle.setAttribute('aria-label','Move dinner and its linked lunch');handle.innerHTML='<span aria-hidden="true">⠿</span>';dinner.insertAdjacentElement('afterend',handle);
handle.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();e.stopPropagation();clear();handle.setPointerCapture?.(e.pointerId);drag={source:day,mealId:dinner.dataset.meal,x:e.clientX,y:e.clientY,active:false,target:null,ghost:null,timer:setTimeout(activate,260)}},{passive:false});
handle.addEventListener('pointermove',e=>{if(!drag||drag.source!==day)return;drag.x=e.clientX;drag.y=e.clientY;if(!drag.active)return;e.preventDefault();if(drag.ghost)drag.ghost.style.top=Math.max(8,e.clientY-70)+'px';mark(e.clientX,e.clientY)},{passive:false});
handle.addEventListener('pointerup',e=>{if(!drag||drag.source!==day)return;e.preventDefault();finish(e.clientX,e.clientY)},{passive:false});handle.addEventListener('pointercancel',clear);handle.addEventListener('lostpointercapture',()=>{if(drag&&!drag.active)clear()})}
function apply(){let style=document.getElementById('dayPairFixStyle');if(!style){style=document.createElement('style');style.id='dayPairFixStyle';style.textContent=`.day h3{padding-right:0!important}.day-drag-handle{display:none!important}.day-pair-handle{display:flex!important;margin:-17px 4px -17px auto!important;position:relative!important;z-index:12!important;width:38px!important;height:34px!important;padding:0!important;align-items:center!important;justify-content:center!important;border-radius:17px!important;border:1px solid rgba(31,75,63,.18)!important;background:#F6EFE4!important;color:#1F4B3F!important;touch-action:none!important;box-shadow:0 1px 0 rgba(31,75,63,.06)!important}.day-pair-handle span{font-size:1.35rem!important;line-height:1!important}.day-pair-handle+.meal{border-top:1px solid var(--hair)!important}`;document.head.appendChild(style)}$all('.day').forEach(bind)}
let queued=false;function run(){if(queued||drag)return;queued=true;requestAnimationFrame(()=>{queued=false;apply()})}
function start(){run();const week=document.getElementById('week');if(week)new MutationObserver(()=>run()).observe(week,{childList:true,subtree:false});window.addEventListener('blur',clear);document.addEventListener('visibilitychange',()=>{if(document.hidden)clear()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();