import{createClient}from'https://esm.sh/@supabase/supabase-js@2';
import{SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY}from'./config.js';
const db=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
let drag=null;const LONG_PRESS=260,EDGE=95,SCROLL=9;
function message(t){const el=document.getElementById('message');if(el)el.innerHTML=t?`<div class="status">${t}</div>`:''}
function clearTarget(){document.querySelectorAll('.day.drag-destination').forEach(n=>n.classList.remove('drag-destination'))}
function reset(){if(!drag)return;clearTimeout(drag.timer);cancelAnimationFrame(drag.raf);drag.sourceDay?.classList.remove('mobile-dragging');clearTarget();drag.ghost?.remove();document.body.classList.remove('meal-drag-active');drag=null}
function dayAt(x,y){const hit=document.elementFromPoint(Math.max(1,Math.min(innerWidth-2,x)),Math.max(1,Math.min(innerHeight-2,y)));return hit?.closest('.day')||null}
function markTarget(x,y){if(!drag)return;clearTarget();const day=dayAt(x,y);drag.targetDay=day;drag.target=day?.dataset.date||null;if(day&&day!==drag.sourceDay)day.classList.add('drag-destination')}
function autoScroll(){if(!drag?.active)return;const dy=drag.y<EDGE?-SCROLL:drag.y>innerHeight-EDGE?SCROLL:0;if(dy){scrollBy(0,dy);markTarget(drag.x,drag.y)}drag.raf=requestAnimationFrame(autoScroll)}
function activate(){if(!drag)return;drag.active=true;document.body.classList.add('meal-drag-active');drag.sourceDay.classList.add('mobile-dragging');const r=drag.sourceDay.getBoundingClientRect(),g=drag.sourceDay.cloneNode(true);g.className='day drag-day-ghost';g.querySelectorAll('.day-drag-handle,.menu,.complete').forEach(n=>n.remove());Object.assign(g.style,{width:r.width+'px',left:r.left+'px',top:Math.max(8,drag.y-55)+'px'});document.body.appendChild(g);drag.ghost=g;navigator.vibrate?.(35);markTarget(drag.x,drag.y);autoScroll()}
async function finish(x,y){if(!drag)return;if(Number.isFinite(x)&&Number.isFinite(y)){drag.x=x;drag.y=y;markTarget(x,y)}const d=drag,{active,target,id,sourceDate}=d;reset();if(!active||!target||target===sourceDate)return;message('Swapping day…');const{error}=await db.rpc('move_meal',{target_meal_id:id,target_date:target});if(error)return message('Could not swap: '+error.message);message('Day swapped. Refreshing…');location.reload()}
function bindDay(day){if(day.dataset.dayDragV4)return;const meal=[...day.querySelectorAll('[data-draggable="true"]')].find(m=>m.querySelector('.muted')?.textContent?.toLowerCase().includes('dinner'))||day.querySelector('[data-draggable="true"]');if(!meal)return;day.dataset.dayDragV4='1';let h=day.querySelector('h3');if(!h)return;let handle=h.querySelector('.day-drag-handle');if(!handle){handle=document.createElement('span');handle.className='day-drag-handle';handle.setAttribute('role','button');handle.setAttribute('aria-label','Move this day');handle.innerHTML='<span class="grip" aria-hidden="true">⠿</span><small>MOVE DAY</small>';h.appendChild(handle)}
 handle.addEventListener('touchstart',e=>{if(e.touches.length!==1)return;const t=e.touches[0];drag={sourceDay:day,sourceDate:day.dataset.date,id:meal.dataset.meal,startX:t.clientX,startY:t.clientY,x:t.clientX,y:t.clientY,active:false,target:null,targetDay:null,timer:setTimeout(activate,LONG_PRESS),ghost:null,raf:null}},{passive:true});
 handle.addEventListener('touchmove',e=>{if(!drag||drag.sourceDay!==day||e.touches.length!==1)return;const t=e.touches[0];drag.x=t.clientX;drag.y=t.clientY;if(!drag.active){if(Math.hypot(t.clientX-drag.startX,t.clientY-drag.startY)>20)reset();return}e.preventDefault();e.stopPropagation();if(drag.ghost)drag.ghost.style.top=Math.max(8,t.clientY-55)+'px';markTarget(t.clientX,t.clientY)},{passive:false});
 handle.addEventListener('touchend',e=>{if(!drag||drag.sourceDay!==day)return;const t=e.changedTouches?.[0];if(drag.active){e.preventDefault();e.stopPropagation()}finish(t?.clientX,t?.clientY)},{passive:false});handle.addEventListener('touchcancel',()=>{if(drag?.sourceDay===day)reset()})}
function enhance(){document.querySelectorAll('.day').forEach(bindDay);document.querySelectorAll('.drag-hint').forEach(n=>n.style.display='none')}
const style=document.createElement('style');style.textContent=`body.meal-drag-active{user-select:none!important;-webkit-user-select:none!important;overscroll-behavior:none!important}.day h3{position:relative!important;padding-right:76px!important}.day-drag-handle{position:absolute;right:0;top:0;display:flex;flex-direction:column;align-items:center;justify-content:center;width:62px;height:48px;color:#1F4B3F;opacity:.68;touch-action:pan-y;cursor:grab}.day-drag-handle .grip{font-size:1.55rem;line-height:1}.day-drag-handle small{font-size:.48rem;letter-spacing:.09em;font-weight:800;margin-top:1px}.meal-drag-active .day-drag-handle{touch-action:none}.day.mobile-dragging{opacity:.28!important}.drag-day-ghost{position:fixed!important;z-index:99999!important;margin:0!important;max-height:150px!important;overflow:hidden!important;background:#F6EFE4!important;border:2px solid #1F4B3F!important;box-shadow:0 14px 34px rgba(31,75,63,.28)!important;transform:scale(.98);opacity:.97!important;pointer-events:none!important}.day.drag-destination{outline:3px dashed #1F4B3F!important;outline-offset:-4px!important;box-shadow:inset 0 0 0 5px rgba(31,75,63,.10)!important}`;document.head.appendChild(style);
const observer=new MutationObserver(()=>requestAnimationFrame(enhance));function start(){enhance();const w=document.getElementById('week');if(w)observer.observe(w,{childList:true,subtree:true})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();