import{createClient}from'https://esm.sh/@supabase/supabase-js@2';
import{SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY}from'./config.js';
const db=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
let drag=null;
const LONG_PRESS=420,EDGE=90,SCROLL=8;
function message(t){const el=document.getElementById('message');if(el)el.innerHTML=t?`<div class="status">${t}</div>`:''}
function reset(){if(!drag)return;clearTimeout(drag.timer);cancelAnimationFrame(drag.raf);drag.el?.classList.remove('mobile-dragging');document.querySelectorAll('.day.drag-destination').forEach(x=>x.classList.remove('drag-destination'));drag.ghost?.remove();drag=null;document.body.classList.remove('meal-drag-active')}
function targetAt(x,y){return document.elementFromPoint(x,y)?.closest('.day')||null}
function markTarget(x,y){if(!drag)return;document.querySelectorAll('.day.drag-destination').forEach(x=>x.classList.remove('drag-destination'));const day=targetAt(x,y);if(day&&day!==drag.sourceDay)day.classList.add('drag-destination');drag.target=day?.dataset.date||null}
function autoScroll(){if(!drag?.active)return;let dy=0;if(drag.y<EDGE)dy=-SCROLL;else if(drag.y>innerHeight-EDGE)dy=SCROLL;if(dy){scrollBy(0,dy);markTarget(drag.x,drag.y)}drag.raf=requestAnimationFrame(autoScroll)}
function activate(el){if(!drag||drag.el!==el)return;drag.active=true;document.body.classList.add('meal-drag-active');el.classList.add('mobile-dragging');try{el.setPointerCapture?.(drag.pointerId)}catch{}const r=el.getBoundingClientRect(),g=el.cloneNode(true);g.className='meal drag-ghost';g.style.width=`${r.width}px`;g.style.left=`${r.left}px`;g.style.top=`${drag.y-r.height/2}px`;document.body.appendChild(g);drag.ghost=g;navigator.vibrate?.(30);autoScroll()}
async function finish(){if(!drag)return;const {active,target,id,sourceDate}=drag;reset();if(!active||!target||target===sourceDate)return;message('Swapping meal…');const{error}=await db.rpc('move_meal',{target_meal_id:id,target_date:target});if(error){message(error.message);return}message('Meal swapped. Refreshing…');location.reload()}
function bind(el){if(el.dataset.mobileDragBound)return;el.dataset.mobileDragBound='1';el.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'||e.target.closest('button,details,summary'))return;if(!e.isPrimary)return;const sourceDay=el.closest('.day');drag={el,id:el.dataset.meal,sourceDay,sourceDate:sourceDay?.dataset.date,startX:e.clientX,startY:e.clientY,x:e.clientX,y:e.clientY,pointerId:e.pointerId,active:false,target:null,timer:null,ghost:null,raf:null};drag.timer=setTimeout(()=>activate(el),LONG_PRESS)} ,{capture:true});el.addEventListener('pointermove',e=>{if(!drag||drag.el!==el||e.pointerId!==drag.pointerId)return;drag.x=e.clientX;drag.y=e.clientY;if(!drag.active){if(Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>14)reset();return}e.preventDefault();if(drag.ghost)drag.ghost.style.top=`${e.clientY-drag.ghost.offsetHeight/2}px`;markTarget(e.clientX,e.clientY)},{capture:true});el.addEventListener('pointerup',e=>{if(!drag||drag.el!==el||e.pointerId!==drag.pointerId)return;if(drag.active){e.preventDefault();e.stopImmediatePropagation()}finish()},{capture:true});el.addEventListener('pointercancel',e=>{if(!drag||drag.el!==el)return;if(!drag.active)reset()},{capture:true});el.addEventListener('lostpointercapture',()=>{if(drag?.el===el&&drag.active)finish()},{capture:true});}
function enhance(){document.querySelectorAll('[data-draggable="true"]').forEach(bind)}
const style=document.createElement('style');style.textContent=`body.meal-drag-active{user-select:none!important;-webkit-user-select:none!important;overscroll-behavior:none!important}.mobile-dragging{opacity:.25!important}.drag-ghost{position:fixed!important;z-index:9999!important;margin:0!important;padding:0 8px!important;background:#F6EFE4!important;border:1px solid rgba(31,75,63,.25)!important;box-shadow:0 12px 30px rgba(31,75,63,.22)!important;transform:scale(1.02);opacity:.96!important;pointer-events:none!important}.drag-ghost .menu,.drag-ghost .drag-hint{display:none!important}.day.drag-destination{outline:3px solid #1F4B3F!important;outline-offset:3px!important;box-shadow:0 0 0 6px rgba(31,75,63,.12)!important}.meal[data-draggable="true"]{touch-action:pan-y}.meal[data-draggable="true"].mobile-dragging{touch-action:none!important}.meal[data-draggable="true"] .meal-copy{cursor:grab}`;document.head.appendChild(style);
const observer=new MutationObserver(enhance);function start(){enhance();const w=document.getElementById('week');if(w)observer.observe(w,{childList:true,subtree:true})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();