import{createClient}from'https://esm.sh/@supabase/supabase-js@2';
import{SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY}from'./config.js';
const db=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
let drag=null;const LONG_PRESS=380,EDGE=95,SCROLL=9;
function message(t){const el=document.getElementById('message');if(el)el.innerHTML=t?`<div class="status">${t}</div>`:''}
function reset(){if(!drag)return;clearTimeout(drag.timer);cancelAnimationFrame(drag.raf);drag.el?.classList.remove('mobile-dragging');document.querySelectorAll('.day.drag-destination').forEach(x=>x.classList.remove('drag-destination'));drag.ghost?.remove();document.body.classList.remove('meal-drag-active');drag=null}
function markTarget(x,y){if(!drag)return;document.querySelectorAll('.day.drag-destination').forEach(n=>n.classList.remove('drag-destination'));const day=document.elementFromPoint(x,y)?.closest('.day')||null;drag.target=day?.dataset.date||null;if(day&&day!==drag.sourceDay)day.classList.add('drag-destination')}
function autoScroll(){if(!drag?.active)return;let dy=drag.y<EDGE?-SCROLL:drag.y>innerHeight-EDGE?SCROLL:0;if(dy){scrollBy(0,dy);markTarget(drag.x,drag.y)}drag.raf=requestAnimationFrame(autoScroll)}
function activate(){if(!drag)return;drag.active=true;document.body.classList.add('meal-drag-active');drag.el.classList.add('mobile-dragging');const r=drag.el.getBoundingClientRect(),g=drag.el.cloneNode(true);g.className='meal drag-ghost';Object.assign(g.style,{width:r.width+'px',left:r.left+'px',top:(drag.y-r.height/2)+'px'});document.body.appendChild(g);drag.ghost=g;navigator.vibrate?.(35);autoScroll()}
async function finish(){if(!drag)return;const d=drag,{active,target,id,sourceDate}=d;reset();if(!active||!target||target===sourceDate)return;message('Swapping meal…');const{error}=await db.rpc('move_meal',{target_meal_id:id,target_date:target});if(error)return message(error.message);message('Meal swapped. Refreshing…');location.reload()}
function bind(el){if(el.dataset.mobileDragV3)return;el.dataset.mobileDragV3='1';el.onpointerdown=el.onpointermove=el.onpointerup=el.onpointercancel=null;el.addEventListener('touchstart',e=>{if(e.target.closest('button,details,summary')||e.touches.length!==1)return;const t=e.touches[0],sourceDay=el.closest('.day');drag={el,id:el.dataset.meal,sourceDay,sourceDate:sourceDay?.dataset.date,startX:t.clientX,startY:t.clientY,x:t.clientX,y:t.clientY,active:false,target:null,timer:setTimeout(activate,LONG_PRESS),ghost:null,raf:null}},{passive:true});el.addEventListener('touchmove',e=>{if(!drag||drag.el!==el||e.touches.length!==1)return;const t=e.touches[0];drag.x=t.clientX;drag.y=t.clientY;if(!drag.active){if(Math.hypot(t.clientX-drag.startX,t.clientY-drag.startY)>18)reset();return}e.preventDefault();e.stopPropagation();if(drag.ghost)drag.ghost.style.top=(t.clientY-drag.ghost.offsetHeight/2)+'px';markTarget(t.clientX,t.clientY)},{passive:false});el.addEventListener('touchend',e=>{if(!drag||drag.el!==el)return;if(drag.active){e.preventDefault();e.stopPropagation()}finish()},{passive:false});el.addEventListener('touchcancel',()=>{if(drag?.el===el)reset()})}
function enhance(){document.querySelectorAll('[data-draggable="true"]').forEach(bind)}
const style=document.createElement('style');style.textContent=`body.meal-drag-active{user-select:none!important;-webkit-user-select:none!important;overscroll-behavior:none!important}.mobile-dragging{opacity:.2!important}.drag-ghost{position:fixed!important;z-index:99999!important;margin:0!important;padding:0 8px!important;background:#F6EFE4!important;border:2px solid #1F4B3F!important;box-shadow:0 14px 34px rgba(31,75,63,.28)!important;transform:scale(1.03);opacity:.98!important;pointer-events:none!important}.drag-ghost .menu,.drag-ghost .drag-hint{display:none!important}.day.drag-destination{outline:3px dashed #1F4B3F!important;outline-offset:-4px!important;box-shadow:inset 0 0 0 5px rgba(31,75,63,.10)!important}.meal[data-draggable="true"]{touch-action:pan-y}.meal[data-draggable="true"].mobile-dragging{touch-action:none!important}`;document.head.appendChild(style);
const observer=new MutationObserver(enhance);function start(){enhance();const w=document.getElementById('week');if(w)observer.observe(w,{childList:true,subtree:true})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();