import{db}from'./db.js?v=release-44900f4bb3';
import{esc,check}from'./shared.js?v=release-44900f4bb3';
import{renderBudget,renderFamily,renderPlanning}from'./more-settings.js?v=release-44900f4bb3';
const target=document.getElementById('moreContent');let section='home',sequence=0;
const state=()=>window.__foodPlanState?.();
async function show(name=section){section=name;const request=++sequence;document.querySelectorAll('[data-more]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.more===name)));const s=state();if(!s?.currentWeek)return;target.textContent='Loading…';try{const detached=document.createElement('div');if(name==='budget')await renderBudget(detached,db,s.currentWeek);else if(name==='family')await renderFamily(detached,db,s.currentWeek);else if(name==='planning')await renderPlanning(detached,db,s);else await home(detached,s);if(request!==sequence)return;target.replaceChildren(detached);}catch(e){if(request===sequence)target.textContent='Could not load this section. '+e.message}}
async function home(container,s){container.innerHTML=`<h3>Household essentials</h3><p class="muted">Check these before shopping. Need to buy adds an item to the current list; changing stock later does not remove a shopping item.</p><form id="addEssential" class="settings-form"><label>Essential name<input name="name" required maxlength="100" placeholder="For example: milk or nappies"></label><label>Shopping category<select name="category">${['Household','Toiletries','Baby','Breakfast','Snacks','Drinks','Dairy & chilled'].map(x=>`<option>${x}</option>`).join('')}</select></label><button type="submit" ${s.offline?'disabled':''}>Add essential</button><p role="status" data-message></p></form><div id="essentialRows">${s.essentials.map(x=>`<section class="essential"><strong>${esc(x.name)}</strong><label>Stock<select data-essential="${x.id}" ${s.offline?'disabled':''}>${[['in_stock','In stock'],['running_low','Running low'],['need_to_buy','Need to buy']].map(([v,l])=>`<option value="${v}" ${x.stock_status===v?'selected':''}>${l}</option>`).join('')}</select></label></section>`).join('')||'<p>Add your regular essentials here so the pre-shop check becomes useful.</p>'}</div>`;
 container.querySelector('#addEssential').onsubmit=async e=>{e.preventDefault();const f=e.target,b=e.submitter;b.disabled=true;const ok=await window.__foodPlanAction('essential',async()=>{check(await db.from('home_essentials').insert({household_id:s.currentWeek.household_id,name:f.elements.name.value.trim(),category:f.elements.category.value,stock_status:'in_stock'}).select('id').single());await window.__foodPlanRefresh()});if(ok)show('home');else f.querySelector('[data-message]').textContent='Could not save; check the connection.';b.disabled=false};
 container.querySelectorAll('[data-essential]').forEach(el=>el.onchange=async()=>{el.disabled=true;await window.__foodPlanAction('essential:'+el.dataset.essential,async()=>{check(await db.from('home_essentials').update({stock_status:el.value,updated_at:new Date().toISOString()}).eq('id',el.dataset.essential).select('id').single());await window.__foodPlanRefresh()});show('home')});}
document.querySelectorAll('[data-more]').forEach(b=>b.onclick=()=>show(b.dataset.more));document.addEventListener('more-open',()=>show());
let changeTimer;document.addEventListener('household-change',()=>{clearTimeout(changeTimer);changeTimer=setTimeout(()=>{if(document.getElementById('morePanel').classList.contains('hidden')||target.querySelector('form:focus-within'))return;show()},400)});
document.addEventListener('session-cleared',()=>{sequence++;target.textContent=''});
