import{createClient}from'https://esm.sh/@supabase/supabase-js@2';
import{SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY}from'./config.js';
const db=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const style=document.createElement('style');style.textContent=`
.recipe-sheet-backdrop[hidden]{display:none!important}.meal{cursor:pointer}.recipe-sheet-backdrop{position:fixed;inset:0;background:rgba(31,75,63,.24);z-index:50;display:flex;align-items:flex-end;justify-content:center;padding-top:50px}.recipe-sheet{width:min(680px,100%);max-height:91vh;overflow:auto;background:#F6EFE4;border-radius:24px 24px 0 0;padding:20px 22px calc(28px + env(safe-area-inset-bottom));box-shadow:0 -14px 40px rgba(46,58,53,.18);color:#2E3A35}.recipe-handle{width:42px;height:4px;border-radius:999px;background:rgba(46,58,53,.25);margin:0 auto 18px}.recipe-close{float:right;width:38px;height:38px!important;padding:0!important;border-radius:50%!important;background:rgba(31,75,63,.09)!important;font-size:1.35rem!important;font-weight:400!important}.recipe-kicker{font:600 11px/1.2 Inter,sans-serif;letter-spacing:1.5px;text-transform:uppercase;color:#7A7A6D;margin-bottom:7px}.recipe-sheet h2{font:600 1.75rem/1.08 'Playfair Display',serif;color:#1F4B3F;margin:0 48px 10px 0}.recipe-allocation{font:400 .88rem/1.45 Inter,sans-serif;color:#5F5F55;margin:0 0 18px}.recipe-leftover{background:rgba(181,82,58,.09);border-radius:12px;padding:10px 12px;margin:0 0 18px;font:400 .84rem/1.4 Inter,sans-serif}.recipe-section{border-top:1px solid rgba(46,58,53,.15);padding-top:16px;margin-top:16px}.recipe-section h3{font:600 1.08rem/1.2 'Playfair Display',serif;color:#1F4B3F;margin:0 0 10px}.recipe-section ul,.recipe-section ol{padding-left:20px;margin:0}.recipe-section li{font:400 .96rem/1.48 Lora,serif;margin:0 0 7px}.recipe-note{font:400 .94rem/1.48 Lora,serif;margin:0}.meal-meta-live{display:flex;gap:10px;align-items:center;margin-top:5px;font:400 .7rem/1.2 Inter,sans-serif;color:#5F5F55}.meal-meta-live span{display:inline-flex;gap:4px;align-items:center}.recipe-loading{padding:28px 0;text-align:center;color:#5F5F55}
`;document.head.appendChild(style);
function ensureSheet(){let back=document.getElementById('recipeSheetBackdrop');if(back)return back;back=document.createElement('div');back.id='recipeSheetBackdrop';back.className='recipe-sheet-backdrop';back.hidden=true;back.innerHTML='<article class="recipe-sheet" role="dialog" aria-modal="true" aria-labelledby="recipeTitle"><div class="recipe-handle"></div><div id="recipeSheetContent"></div></article>';document.body.appendChild(back);back.addEventListener('click',e=>{if(e.target===back)closeSheet()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!back.hidden)closeSheet()});return back}
function closeSheet(){const b=document.getElementById('recipeSheetBackdrop');if(b)b.hidden=true;document.body.style.overflow=''}
async function fetchMeal(id){const fields='id,title,slot,meal_mode,source_meal_id,cuisine,method,flavour_note,child_note,storage_note,portions,recipe_ingredients,prep_minutes';const{data,error}=await db.from('meals').select(fields).eq('id',id).single();if(error)throw error;return data}
function section(title,body){return body?`<section class="recipe-section"><h3>${title}</h3>${body}</section>`:''}
function renderMeal(meal,source){const recipe=source||meal,allocation=meal.portions?.allocation||recipe.portions?.allocation||'';const ingredients=recipe.recipe_ingredients||[];const method=meal.meal_mode==='planned_leftover'?(meal.method||[]):(recipe.method||[]);const leftover=meal.meal_mode==='planned_leftover'?`<div class="recipe-leftover">Planned lunch · the same complete meal prepared from the source dinner.</div>`:'';return `<button class="recipe-close" aria-label="Close recipe">×</button><div class="recipe-kicker">${esc(meal.slot)}${recipe.cuisine?' · '+esc(recipe.cuisine):''}</div><h2 id="recipeTitle">${esc(meal.title)}</h2>${allocation?`<p class="recipe-allocation">${esc(allocation)}</p>`:''}${leftover}${section('Ingredients',ingredients.length?`<ul>${ingredients.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'')}${section(meal.meal_mode==='planned_leftover'?'Reheat & serve':'Method',method.length?`<ol>${method.map(x=>`<li>${esc(x)}</li>`).join('')}</ol>`:'')}${section('Flavour',recipe.flavour_note?`<p class="recipe-note">${esc(recipe.flavour_note)}</p>`:'')}${section('Barney',recipe.child_note?`<p class="recipe-note">${esc(recipe.child_note)}</p>`:'')}${section('Storage & reheating',(recipe.storage_note||meal.storage_note)?`<p class="recipe-note">${esc(meal.storage_note||recipe.storage_note)}</p>`:'')}`}
async function openMeal(id){const back=ensureSheet(),content=document.getElementById('recipeSheetContent');back.hidden=false;document.body.style.overflow='hidden';content.innerHTML='<div class="recipe-loading">Loading recipe…</div>';try{const meal=await fetchMeal(id);let source=null;if(meal.meal_mode==='planned_leftover'&&meal.source_meal_id)source=await fetchMeal(meal.source_meal_id);content.innerHTML=renderMeal(meal,source);content.querySelector('.recipe-close').onclick=closeSheet}catch(e){content.innerHTML='<button class="recipe-close" aria-label="Close recipe">×</button><h2 id="recipeTitle">Recipe unavailable</h2><p class="recipe-note">The meal is still on the plan, but its recipe detail could not be loaded.</p>';content.querySelector('.recipe-close').onclick=closeSheet}}
function hydrateMeta(){document.querySelectorAll('.meal-meta-live').forEach(x=>x.remove())}
document.addEventListener('click',e=>{const meal=e.target.closest('.meal[data-meal]');if(!meal||e.target.closest('button,details,summary,.menu-pop'))return;openMeal(meal.dataset.meal)});
const obs=new MutationObserver(()=>queueMicrotask(hydrateMeta));const start=()=>{ensureSheet();hydrateMeta();const week=document.getElementById('week');if(week)obs.observe(week,{childList:true,subtree:true})};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();