import{db}from'./db.js?v=release-c5a1ada254';
import{esc,localDate,addDays,fmt,dates,check,SECTIONS,allocation,Latest,ruleMatches}from'./shared.js?v=release-c5a1ada254';
const $=id=>document.getElementById(id),latest=new Latest();
let user=null,weeks=[],currentWeek=null,meals=[],shop=[],members=[],prefs=[],feedback=[],essentials=[],view='week',shopFilter='remaining',dayFocus='',channel=null,booting=null,offline=false;
const pending=new Set();let refreshTimer;let syncState='Connecting…';
export const state=()=>({user,weeks,currentWeek,meals,shop,members,prefs,feedback,essentials,offline});
window.__foodPlanDb=db;window.__foodPlanCurrentWeek=()=>currentWeek;window.__foodPlanState=state;
function say(message,error=false){$('message').textContent=message;$('message').className=error?'status error':'status';$('message').hidden=!message}
function sync(message){syncState=message;$('syncState').textContent=message}
function loginNote(text){$('loginStatus').textContent=text}
const editable=()=>!offline&&currentWeek?.status==='current';
const cacheKey=()=>user?'food-plan-snapshot:'+user.id:null;
function storeSnapshot(){try{localStorage.setItem(cacheKey(),JSON.stringify({saved:Date.now(),weeks,currentWeek,meals,shop,members,prefs,feedback,essentials}))}catch{}}
function readSnapshot(){try{const c=JSON.parse(localStorage.getItem(cacheKey()));if(!c||!c.currentWeek)return false;({weeks,currentWeek,meals,shop,members,prefs,feedback,essentials}=c);offline=true;render();sync('Offline · saved '+new Date(c.saved).toLocaleString('en-GB'));return true}catch{return false}}
async function action(key,operation){if(pending.has(key))return;pending.add(key);sync('Saving…');try{if(!navigator.onLine||offline)throw new Error('Reconnect before making changes. Your saved plan is available to read.');await operation();sync('Saved');return true}catch(e){say(e.message,true);sync('Save failed · retry when connected');return false}finally{pending.delete(key)}}
async function loadWeeks(){weeks=check(await db.from('weeks').select('*').order('start_date'))||[];const keep=weeks.find(w=>w.id===currentWeek?.id),t=localDate();const selected=keep||weeks.find(w=>w.start_date<=t&&w.end_date>=t)||weeks.find(w=>w.status==='current')||weeks.at(-1);if(!selected){say('No weeks have been published for your household yet.');return}await selectWeek(selected.id)}
export async function refresh(){if(!user)return;try{await loadWeeks()}catch(e){if(!navigator.onLine&&readSnapshot())return;say('Could not load your plan. '+e.message,true);sync('Load failed')}}
async function selectWeek(id){const week=weeks.find(w=>w.id===id);if(!week)return;const request=latest.next();sync('Loading…');try{const result=await Promise.all([
 db.from('meals').select('*').eq('week_id',week.id).order('scheduled_date').order('slot'),
 db.from('meals').select('*').eq('scheduled_date',week.start_date).eq('slot','lunch').neq('week_id',week.id),
 db.from('shopping_items').select('*').eq('week_id',week.id).order('name'),
 db.from('household_members').select('*').eq('household_id',week.household_id).order('created_at'),
 db.from('preferences').select('*').eq('household_id',week.household_id).order('created_at'),
 db.from('meal_feedback').select('*').eq('household_id',week.household_id).order('created_at',{ascending:false}),
 db.from('home_essentials').select('*').eq('household_id',week.household_id).order('name')]);const data=result.map(check);if(!latest.is(request))return;currentWeek=week;meals=[...(data[0]||[]),...(data[1]||[])];shop=data[2]||[];members=data[3]||[];prefs=data[4]||[];feedback=data[5]||[];essentials=data[6]||[];offline=false;render();storeSnapshot();subscribe();sync('Shared household · up to date');document.dispatchEvent(new CustomEvent('plan-loaded'));}catch(e){if(!latest.is(request))return;if(!navigator.onLine&&readSnapshot())return;say('Could not load this week. '+e.message,true);sync('Load failed');}}
function mealRow(m){const done=m.execution_status==='done',avoids=ruleMatches(m,prefs);return `<article class="meal ${done?'done':''}" data-meal="${esc(m.id)}" data-status="${esc(m.execution_status)}" data-slot="${esc(m.slot)}"><div class="row"><div class="meal-main">${editable()&&m.week_id===currentWeek.id?`<button class="complete ${done?'checked':''}" data-status-id="${m.id}" data-next="${done?'upcoming':'done'}" aria-label="${done?'Mark not completed':'Mark completed'}: ${esc(m.title)}">${done?'✓':''}</button>`:'<span class="meal-static" aria-hidden="true"></span>'}<div class="meal-copy"><div class="muted">${esc(m.slot)}${m.meal_mode==='planned_leftover'?' · saved from dinner':''}</div><button class="recipe-open title" data-recipe="${m.id}">${esc(m.title)}</button>${m.prep_minutes?`<small>${Number(m.prep_minutes)} min prep</small>`:''}${avoids.length?'<small class="error">Check family preference: '+esc(avoids.map(x=>x.subject).join(', '))+'</small>':''}${done?'<small>Completed</small>':''}</div></div>${editable()&&m.week_id===currentWeek.id&&m.slot==='dinner'&&!done?`<button class="move-action" data-move="${m.id}" title="Hold and drag, or tap to move" aria-label="Drag or tap to move ${esc(m.title)} to another day">⠿</button>`:''}</div></article>`}
function renderWeek(){const ds=dates(currentWeek.start_date,currentWeek.end_date);$('week').innerHTML=ds.map(d=>`<section class="card day ${dayFocus&&dayFocus!==d?'hidden':''}" data-date="${d}"><h3><span>${fmt(d,{weekday:'long'})}</span> <em>${fmt(d,{day:'numeric',month:'long'})}</em></h3>${meals.filter(m=>m.scheduled_date===d).sort((a,b)=>(a.slot==='lunch'?0:1)-(b.slot==='lunch'?0:1)).map(mealRow).join('')||'<p>No meals planned.</p>'}</section>`).join('');const carry=meals.filter(m=>m.scheduled_date>currentWeek.end_date);if(carry.length)$('week').insertAdjacentHTML('beforeend',`<section id="boundaryLunch" class="card"><h3>Ready for next week</h3>${carry.map(m=>`<p><strong>${esc(fmt(m.scheduled_date))}</strong> · ${esc(m.title)}<br><small>${m.meal_mode==='planned_leftover'?'Lunch saved from the source dinner':'Separate lunch paired with the dinner schedule'}</small></p>`).join('')}</section>`);$('dayStrip').innerHTML=`<button class="week-overview ${!dayFocus?'active':''}" data-day="">All</button>`+ds.map(d=>`<button class="day-chip ${dayFocus===d?'active':''}" data-day="${d}"><span>${fmt(d,{weekday:'short'})}</span><b>${fmt(d,{day:'numeric'})}</b></button>`).join('');document.dispatchEvent(new CustomEvent('week-rendered'));}
function renderTonight(){const today=localDate(),dinner=meals.find(m=>m.scheduled_date===today&&m.slot==='dinner');$('tonight').hidden=!dinner;if(!dinner)return;$('tonight').innerHTML=`<div class="eyebrow">${dinner.execution_status==='done'?'Tonight · completed':'Tonight'}</div><button class="recipe-open tonight-title" data-recipe="${dinner.id}">${esc(dinner.title)}</button><p>${esc(allocation(dinner,meals))}</p>`}
function sectionFor(item){return item.shopping_section!=='Other'?item.shopping_section:({food:'Other food',breakfast:'Breakfast',snack:'Snacks',toiletry:'Toiletries',household:'Household & cleaning'}[item.category]||'Other')}
function renderShop(){const known=new Set([...$('shopList').querySelectorAll('.shopping-section')].map(x=>x.dataset.section));const opened=new Set([...$('shopList').querySelectorAll('.shopping-section[open]')].map(x=>x.dataset.section));const groups=new Map();shop.forEach(x=>{const s=sectionFor(x);if(!groups.has(s))groups.set(s,[]);groups.get(s).push(x)});$('shopProgress').textContent=`${shop.filter(x=>x.purchased).length} bought · ${shop.filter(x=>x.have_at_home).length} already at home · ${shop.filter(x=>!x.purchased&&!x.have_at_home).length} remaining`;
 $('shopList').innerHTML=[...groups].sort(([a],[b])=>SECTIONS.indexOf(a)-SECTIONS.indexOf(b)).map(([s,items])=>{const shown=items.filter(x=>shopFilter==='all'||shopFilter==='bought'&&x.purchased||shopFilter==='home'&&x.have_at_home||shopFilter==='remaining'&&!x.purchased&&!x.have_at_home);if(!shown.length)return '';return `<details class="shopping-section" data-section="${esc(s)}" ${opened.has(s)||!known.has(s)?'open':''}><summary>${esc(s)} <small>${items.filter(x=>x.purchased||x.have_at_home).length}/${items.length}</small></summary>${shown.map(x=>`<div class="shopping-row" data-shop-id="${x.id}"><label class="${x.purchased?'shop-bought':''}"><input type="checkbox" data-tick="${x.id}" ${x.purchased?'checked':''} ${editable()?'':'disabled'}><span>${esc(x.name)}</span><span>${esc(x.quantity)} ${esc(x.unit)}</span></label><details class="item-options"><summary aria-label="Options for ${esc(x.name)}">Details</summary><label><input type="checkbox" data-home="${x.id}" ${x.have_at_home?'checked':''} ${editable()?'':'disabled'}> Already at home</label><label>Estimated pack cost (£)<input type="number" min="0" step=".01" value="${esc(x.estimated_cost??'')}" data-price="${x.id}" ${editable()?'':'disabled'}></label><small>Cost for the listed quantity, not per unit.</small></details></div>`).join('')}</details>`}).join('')||'<p>No items in this view.</p>';}
function render(){if(!currentWeek)return;$('main').classList.remove('hidden');$('login').classList.add('hidden');$('period').textContent=fmt(currentWeek.start_date)+' – '+fmt(currentWeek.end_date);const i=weeks.findIndex(w=>w.id===currentWeek.id);$('prevWeek').disabled=i===0||offline;$('nextWeek').disabled=i===weeks.length-1||offline;$('addShopForm').hidden=!editable();renderWeek();renderTonight();renderShop();setView(view,false);$('accountEmail').textContent=user?.email||'';}
export function setView(next,refreshMore=true){view=next;for(const name of ['week','shop','more'])$(name==='more'?'morePanel':name).classList.toggle('hidden',name!==view);$('dayStrip').hidden=view!=='week';$('tonight').hidden=view!=='week'||!meals.some(m=>m.scheduled_date===localDate()&&m.slot==='dinner');$('weekControls').hidden=view!=='week';for(const n of ['week','shop','more'])$(n+'Tab').setAttribute('aria-current',n===view?'page':'false');if(view==='more'&&refreshMore)document.dispatchEvent(new CustomEvent('more-open'));}
async function subscribe(){const key=currentWeek.household_id;if(channel?.key===key)return;if(channel)await db.removeChannel(channel);channel=db.channel('household:'+key);channel.key=key;for(const table of ['shopping_items','meals','weeks','household_members','preferences','home_essentials','meal_feedback','shop_transactions'])channel.on('postgres_changes',{event:'*',schema:'public',table},()=>{clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>refresh(),180);document.dispatchEvent(new CustomEvent('household-change',{detail:{table}}))});channel.subscribe(status=>{if(status==='SUBSCRIBED')sync('Shared household · live');if(['CHANNEL_ERROR','TIMED_OUT','CLOSED'].includes(status))sync('Live updates unavailable · refresh to check')});}
async function boot(){if(booting)return booting;booting=(async()=>{const {data,error}=await db.auth.getSession();if(error)throw error;if(!data.session)return;user=data.session.user;await refresh()})();try{await booting}catch(e){loginNote(e.message)}finally{booting=null}}
function clearSession(){latest.next();if(cacheKey())localStorage.removeItem(cacheKey());user=null;weeks=[];meals=[];shop=[];currentWeek=null;offline=false;if(channel){db.removeChannel(channel);channel=null}$('main').classList.add('hidden');$('login').classList.remove('hidden');$('password').value='';document.dispatchEvent(new Event('session-cleared'));}
let recovery=false;db.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'){clearSession();return}if(event==='PASSWORD_RECOVERY'){recovery=true;$('normalLogin').classList.add('hidden');$('recovery').classList.remove('hidden');$('main').classList.add('hidden');$('login').classList.remove('hidden');return}if((event==='SIGNED_IN'||event==='INITIAL_SESSION')&&!recovery)setTimeout(boot,0)});
const formSwitch=register=>{$('register').classList.toggle('hidden',!register);$('normalLogin').classList.toggle('hidden',register);loginNote('')};$('showRegister').onclick=()=>formSwitch(true);$('registerBack').onclick=()=>formSwitch(false);
$('signIn').onclick=async()=>{if(pending.has('login'))return;pending.add('login');try{const{error}=await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)throw error;await boot()}catch(e){loginNote(e.message)}finally{pending.delete('login')}};
$('password').addEventListener('keydown',e=>{if(e.key==='Enter')$('signIn').click()});
$('registerSubmit').onclick=async()=>{const {error}=await db.auth.signUp({email:$('registerEmail').value.trim(),password:$('registerPassword').value,options:{emailRedirectTo:location.origin+location.pathname}});loginNote(error?error.message:'Check your email, verify your account, then sign in. An existing household invitation is required.');};
$('resetPassword').onclick=async()=>{const email=$('email').value.trim();if(!email)return loginNote('Enter your email address first.');const{error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});loginNote(error?error.message:'If an account exists, a recovery email has been sent.');};
$('savePassword').onclick=async()=>{const password=$('newPassword').value;if(password.length<8||password!==$('confirmPassword').value)return loginNote('Use at least 8 characters and make both passwords match.');const{error}=await db.auth.updateUser({password});if(error)return loginNote(error.message);recovery=false;$('recovery').classList.add('hidden');$('normalLogin').classList.remove('hidden');history.replaceState({},'',location.pathname);await boot()};
$('signOut').onclick=async()=>{const {error}=await db.auth.signOut();if(error){say(error.message,true);return}clearSession()};
$('refreshPlan').onclick=refresh;for(const v of ['week','shop','more'])$(v+'Tab').onclick=()=>setView(v);
$('prevWeek').onclick=()=>selectWeek(weeks[weeks.findIndex(w=>w.id===currentWeek.id)-1]?.id);$('nextWeek').onclick=()=>selectWeek(weeks[weeks.findIndex(w=>w.id===currentWeek.id)+1]?.id);$('todayWeek').onclick=()=>selectWeek(weeks.find(w=>w.start_date<=localDate()&&w.end_date>=localDate())?.id);
$('dayStrip').onclick=e=>{const b=e.target.closest('[data-day]');if(b){dayFocus=b.dataset.day;renderWeek()}};
$('shopFilters').onclick=e=>{const b=e.target.closest('[data-filter]');if(!b)return;shopFilter=b.dataset.filter;$('shopFilters').querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderShop()};
document.addEventListener('click',async e=>{const b=e.target.closest('[data-status-id]');if(b){b.disabled=true;await action('meal:'+b.dataset.statusId,async()=>{check(await db.rpc('set_meal_status',{target_meal_id:b.dataset.statusId,new_status:b.dataset.next,note:null}));await refresh()});b.disabled=false}const move=e.target.closest('[data-move]');if(move)openMove(move.dataset.move);});
function openMove(id){const m=meals.find(x=>x.id===id),dialog=$('moveDialog');dialog.innerHTML=`<form method="dialog"><h2>Move dinner</h2><p>${esc(m.title)}</p><label>Choose day<select id="moveDate">${dates(currentWeek.start_date,currentWeek.end_date).filter(d=>d!==m.scheduled_date).map(d=>`<option value="${d}">${esc(fmt(d))}</option>`).join('')}</select></label><p>The paired next-day lunch moves too. An occupied dinner is swapped.</p><p class="error">Check nursery, attendance and preparation needs before moving.</p><div class="actions"><button value="cancel">Cancel</button><button type="button" id="confirmMove" class="primary">Move dinner</button></div><p id="moveError" role="status"></p></form>`;dialog.showModal();dialog.querySelector('#confirmMove').onclick=async e=>{e.target.disabled=true;const ok=await action('move',async()=>{check(await db.rpc('move_meal',{target_meal_id:id,target_date:dialog.querySelector('#moveDate').value}));await refresh()});if(ok)dialog.close();else dialog.querySelector('#moveError').textContent=$('message').textContent;e.target.disabled=false};}
$('shopList').onchange=async e=>{const el=e.target,id=el.dataset.tick||el.dataset.home||el.dataset.price;if(!id)return;const item=shop.find(x=>x.id===id);el.disabled=true;await action('shop:'+id,async()=>{if(el.dataset.tick)check(await db.rpc('set_shopping_tick',{item_id:id,expected:item.purchased,next_value:el.checked}));else{const patch=el.dataset.home?{have_at_home:el.checked}:{estimated_cost:el.value===''?null:Number(el.value)};if(patch.estimated_cost!=null&&(!Number.isFinite(patch.estimated_cost)||patch.estimated_cost<0))throw new Error('Enter a valid price.');check(await db.from('shopping_items').update(patch).eq('id',id).select('id').single())}await refresh()});el.disabled=false;};
$('addShopForm').onsubmit=async e=>{e.preventDefault();const f=e.target,button=e.submitter;button.disabled=true;await action('addShop',async()=>{const name=f.elements.name.value.trim(),quantity=Number(f.elements.quantity.value);if(!name||quantity<=0)throw new Error('Enter an item and quantity.');check(await db.from('shopping_items').insert({week_id:currentWeek.id,name,quantity,unit:f.elements.unit.value.trim()||'item',shopping_section:f.elements.section.value,category:'other'}).select('id').single());f.reset();await refresh()});button.disabled=false};
window.addEventListener('offline',()=>{offline=true;sync('Offline · read only');render()});window.addEventListener('online',()=>refresh());document.addEventListener('visibilitychange',()=>{if(!document.hidden&&user)refresh()});
window.__foodPlanRefresh=refresh;window.__foodPlanAction=action;
boot();
import('./week-details.js?v=release-c5a1ada254').catch(()=>say('Recipe tools could not load. Refresh to retry.',true));
import('./ui-rustic.js?v=release-c5a1ada254').catch(()=>say('Settings could not load. Refresh to retry.',true));

setTimeout(()=>import('./drag-fix.js?v=release-c5a1ada254').catch(()=>say('Drag could not load. Tap the dotted handle to move dinner.',true)),500);

if("serviceWorker" in navigator)navigator.serviceWorker.register("./sw.js?v=release-c5a1ada254").catch(()=>{});

let updatedController=false;navigator.serviceWorker?.addEventListener('controllerchange',()=>{if(updatedController)return;updatedController=true;if(navigator.serviceWorker.controller&&document.visibilityState==='visible')location.reload()});
