import{db}from'./db.js?v=release-c5a1ada254';
import{esc,check,allocation,scaledLabel,scheduleNote}from'./shared.js?v=release-c5a1ada254';
let request=0,returnFocus=null,wakeLock=null,timer=null,activeMeal=null;
const dialog=document.createElement('dialog');dialog.id='recipeDialog';dialog.className='recipe-sheet';document.body.append(dialog);
const state=()=>window.__foodPlanState?.();
function legacyIngredients(recipe){return (recipe.recipe_ingredients||[]).map(label=>{const i=label.indexOf(' — ');return {label:i<0?label:label.slice(0,i),prep:i<0?'':label.slice(i+3)}})}
async function getMeal(id){const cached=state()?.meals.find(m=>m.id===id);if(cached)return cached;if(state()?.offline)throw new Error('This source recipe is not in the saved offline plan.');return check(await db.from('meals').select('*').eq('id',id).single())}
function notes(recipe,meal){return [['Flavour',recipe.flavour_note],['For Barney',recipe.child_note],['Storage & reheating',scheduleNote(meal.storage_note||recipe.storage_note,meal,state().meals)]].filter(([,t])=>t).map(([h,t])=>`<section class="recipe-card"><h3>${h}</h3><p>${esc(t)}</p></section>`).join('')}
function cookKey(){return 'cook:'+state()?.user?.id+':'+activeMeal.id+':'+activeMeal.recipe_revision}
function ticks(){try{return JSON.parse(sessionStorage.getItem(cookKey()))||{}}catch{return {}}}
function applyTicks(){const saved=ticks();dialog.querySelectorAll('[data-cook-tick]').forEach(x=>{x.checked=!!saved[x.dataset.cookTick];x.closest('li').classList.toggle('cooked',x.checked)})}
async function openRecipe(id){const token=++request;returnFocus=document.activeElement;activeMeal=null;dialog.innerHTML='<p role="status">Loading recipe…</p><button data-close>Close</button>';if(!dialog.open)dialog.showModal();try{const meal=await getMeal(id),recipe=meal.meal_mode==='planned_leftover'?await getMeal(meal.source_meal_id):meal;if(token!==request||!dialog.open)return;activeMeal=recipe;const s=state(),ingredients=recipe.recipe_detail?.ingredients||legacyIngredients(recipe);const steps=meal.meal_mode==='planned_leftover'?(meal.method?.length?meal.method:['Take the reserved complete lunch portion from the fridge. Follow the storage and reheating guidance below; heat the hot components thoroughly and keep salad components separate.']):(recipe.recipe_detail?.method||recipe.method||[]);
 dialog.innerHTML=`<div class="recipe-toolbar"><button data-close aria-label="Close recipe">×</button><span class="eyebrow">${esc(meal.slot)} · ${esc(recipe.cuisine||'Recipe')}</span></div><h2 id="recipeTitle">${esc(meal.title)}</h2><p class="recipe-allocation">${esc(allocation(meal,s.meals))}</p><div class="recipe-controls"><button id="cookMode" aria-pressed="false">Cooking mode</button><label>Quantity preview<select id="recipeScale"><option value="1">Planned quantities</option><option value=".5">Half batch</option><option value="1.5">One and a half batches</option><option value="2">Double batch</option></select></label></div><p id="scaleNote" class="muted" hidden>Preview only: quantities change, cooking temperatures and timings stay as written. Check seasoning and batch size.</p><section class="recipe-section"><h3>Ingredients & preparation</h3><ul class="recipe-ingredients">${ingredients.map((x,i)=>`<li><label class="cook-check"><input type="checkbox" data-cook-tick="ingredient-${i}" aria-label="Prepared: ${esc(x.label)}"><span class="recipe-ingredient-main" data-ingredient="${i}">${esc(x.label)}</span></label>${x.prep?`<span class="recipe-ingredient-prep">${esc(x.prep)}</span>`:''}</li>`).join('')}</ul></section><section class="recipe-section"><h3>${meal.meal_mode==='planned_leftover'?'Reheat & serve':'Cook'}</h3><ol class="recipe-method">${steps.map((t,i)=>`<li><label class="cook-check"><input type="checkbox" data-cook-tick="step-${i}" aria-label="Complete step ${i+1}"><span>${esc(t)}</span></label></li>`).join('')}</ol></section><section class="cooking-tools" hidden><h3>Cooking tools</h3><label>Timer (minutes)<input id="timerMinutes" type="number" min="1" max="300" value="10"></label><button id="startTimer">Start timer</button><button id="stopTimer">Stop</button><p id="timerStatus" role="status"></p><button id="awake" aria-pressed="false">Keep screen awake</button><p id="awakeStatus" role="status"></p><button id="resetTicks">Reset cooking checklist</button><p class="muted">Checklist is private to this device and session.</p></section><div class="recipe-notes">${notes(recipe,meal)}</div><section class="recipe-section"><h3>How was it?</h3><form id="feedbackForm"><label>Verdict<select name="rating"><option value="loved">Cook again</option><option value="needs_adjustment">Adjust next time</option><option value="do_not_suggest">Avoid next time</option></select></label><label>Notes<textarea name="notes" maxlength="1000" placeholder="What worked, or what would you change?"></textarea></label><button type="submit" ${s.offline?'disabled':''}>Save feedback</button><p role="status" id="feedbackStatus"></p></form></section>`;
 dialog.setAttribute('aria-labelledby','recipeTitle');dialog.querySelector('[data-close]').focus();applyTicks();dialog.querySelector('#cookMode').onclick=e=>{const on=!dialog.classList.contains('cooking');dialog.classList.toggle('cooking',on);e.target.setAttribute('aria-pressed',String(on));dialog.querySelector('.cooking-tools').hidden=!on};
 dialog.querySelector('#recipeScale').onchange=e=>{const f=Number(e.target.value);dialog.querySelectorAll('[data-ingredient]').forEach(el=>el.textContent=scaledLabel(ingredients[Number(el.dataset.ingredient)].label,f));dialog.querySelector('#scaleNote').hidden=f===1};
 dialog.querySelector('#startTimer').onclick=()=>{const minutes=Number(dialog.querySelector('#timerMinutes').value);if(!Number.isFinite(minutes)||minutes<1||minutes>300)return;clearInterval(timer);const ends=Date.now()+minutes*60000;const update=()=>{const seconds=Math.max(0,Math.ceil((ends-Date.now())/1000));dialog.querySelector('#timerStatus').textContent=seconds?Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0')+' remaining':'Timer finished';if(!seconds){clearInterval(timer);navigator.vibrate?.([200,100,200])}};update();timer=setInterval(update,1000)};
 dialog.querySelector('#stopTimer').onclick=()=>{clearInterval(timer);dialog.querySelector('#timerStatus').textContent='Timer stopped'};
 dialog.querySelector('#awake').onclick=async e=>{try{if(wakeLock){await wakeLock.release();wakeLock=null;e.target.setAttribute('aria-pressed','false');dialog.querySelector('#awakeStatus').textContent='Screen can sleep';return}if(!navigator.wakeLock)throw new Error('Keep-awake is not supported by this browser.');wakeLock=await navigator.wakeLock.request('screen');e.target.setAttribute('aria-pressed','true');dialog.querySelector('#awakeStatus').textContent='Screen stays awake while this recipe is open';wakeLock.addEventListener('release',()=>{wakeLock=null;e.target.setAttribute('aria-pressed','false')})}catch(err){dialog.querySelector('#awakeStatus').textContent=err.message}};
 dialog.querySelector('#resetTicks').onclick=()=>{sessionStorage.removeItem(cookKey());applyTicks()};
 dialog.querySelector('#feedbackForm').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;const f=e.target;const ok=await window.__foodPlanAction('feedback',async()=>{check(await db.from('meal_feedback').insert({household_id:s.currentWeek.household_id,meal_id:recipe.id,meal_title:recipe.title,rating:f.elements.rating.value,notes:f.elements.notes.value.trim()||null,user_id:s.user.id}).select('id').single())});dialog.querySelector('#feedbackStatus').textContent=ok?'Saved for future planning.':'Could not save. Reconnect and try again.';b.disabled=false};
 }catch(e){if(token===request)dialog.innerHTML='<button data-close>Close recipe</button><h2>Recipe unavailable</h2><p>'+esc(e.message)+'</p>'}}
dialog.onclick=e=>{if(e.target.closest('[data-close]'))dialog.close()};dialog.onchange=e=>{const x=e.target;if(x.dataset.cookTick){const saved=ticks();saved[x.dataset.cookTick]=x.checked;sessionStorage.setItem(cookKey(),JSON.stringify(saved));x.closest('li').classList.toggle('cooked',x.checked)}};
dialog.addEventListener('close',()=>{request++;dialog.classList.remove('cooking');clearInterval(timer);wakeLock?.release();wakeLock=null;if(returnFocus?.isConnected)returnFocus.focus()});
document.addEventListener('click',e=>{const b=e.target.closest('[data-recipe]');if(b)openRecipe(b.dataset.recipe)});document.addEventListener('session-cleared',()=>dialog.close());
